[package]
name = "www-rust-lang-org"
version = "0.1.0"
authors = ["Ashley Williams <ashley666ashley@gmail.com>"]
edition = "2018"

[dependencies]
lazy_static = "1.2.0"
fluent = "0.5"
fluent-bundle = "0.6.0"
fluent-syntax = "0.9.0"
rand = "0.6"
regex = "1"
rocket = "0.4.1"
serde = "1.0"
serde_derive = "1.0"
serde_yaml = "0.8.7"
sass-rs = "0.2.1"
reqwest = "0.9.5"
toml = "0.4"
serde_json = "1.0"
rust_team_data = { git = "https://github.com/rust-lang/team" }

[dependencies.rocket_contrib]
version = "*"
default-features = false
features = ["handlebars_templates"]
